name: Ruby

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install -j $(getconf _NPROCESSORS_ONLN) --retry 3

    - name: Run tests
      run: bundle exec rake
